/*
 *  ARToolKitCore_bindings.cpp
 *  artoolkit5-wasm
 *
 *  This file is part of artoolkit5-wasm - AR-js-org.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in
 *  all copies or substantial portions of the Software.
 *
 *  artoolkit5-wasm is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 *  or FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. See the MIT License
 *  for more details.
 *
 *  You should have received a copy of the MIT License along with
 *  artoolkit5-wasm. If not, see <https://opensource.org/licenses/MIT>.
 *
 *  This file is compiled together with ARToolkit5 (WebARKitLib), which is
 *  licensed under the GNU Lesser General Public License v3.0, into the
 *  WebAssembly binary distributed in this package.
 *
 *  Copyright (c) 2026 AR-js-org
 *
 *  Author(s): Walter Perdan @kalwalt https://github.com/kalwalt
 *
 */

#include "ARToolKitCore.h"
#include <emscripten/bind.h>

using namespace emscripten;
using arjs::artoolkit5::ARToolKitCore;

EMSCRIPTEN_BINDINGS(ARToolKitCore_bindings)
{
    class_<ARToolKitCore>("ARToolKitCore")
        .constructor()
        .function("detectMarker", &ARToolKitCore::detectMarker)
        .function("getMarkerInfo", &ARToolKitCore::getMarkerInfo)
        .function("getMarkerNum", &ARToolKitCore::getMarkerNum)
        .function("teardown", &ARToolKitCore::teardown)
        .function("_loadCamera", &ARToolKitCore::loadCamera)
        .function("setup", &ARToolKitCore::setup)
        .function("addMarker", &ARToolKitCore::addMarker)
        .function("setMarkerInfoDir", &ARToolKitCore::setMarkerInfoDir)
        .function("setMarkerInfoVertex", &ARToolKitCore::setMarkerInfoVertex)
        .function("getCameraLens", &ARToolKitCore::getCameraLens)
        .function("recalculateCameraLens", &ARToolKitCore::recalculateCameraLens)
        .function("passVideoData", &ARToolKitCore::passVideoData)

        .function("setLogLevel", &ARToolKitCore::setLogLevel)
        .function("getLogLevel", &ARToolKitCore::getLogLevel)

        .function("setPatternDetectionMode", &ARToolKitCore::setPatternDetectionMode)
        .function("getPatternDetectionMode", &ARToolKitCore::getPatternDetectionMode)

        .function("setProjectionNearPlane", &ARToolKitCore::setProjectionNearPlane)
        .function("getProjectionNearPlane", &ARToolKitCore::getProjectionNearPlane)

        .function("setProjectionFarPlane", &ARToolKitCore::setProjectionFarPlane)
        .function("getProjectionFarPlane", &ARToolKitCore::getProjectionFarPlane)

        .function("setPattRatio", &ARToolKitCore::setPattRatio)
        .function("getPattRatio", &ARToolKitCore::getPattRatio)

        .function("setMatrixCodeType", &ARToolKitCore::setMatrixCodeType)
        .function("getMatrixCodeType", &ARToolKitCore::getMatrixCodeType)

        .function("setThresholdMode", &ARToolKitCore::setThresholdMode)
        .function("getThresholdMode", &ARToolKitCore::getThresholdMode)

        .function("setThreshold", &ARToolKitCore::setThreshold)
        .function("getThreshold", &ARToolKitCore::getThreshold)

        .function("setLabelingMode", &ARToolKitCore::setLabelingMode)
        .function("getLabelingMode", &ARToolKitCore::getLabelingMode)

        .function("setImageProcMode", &ARToolKitCore::setImageProcMode)
        .function("getImageProcMode", &ARToolKitCore::getImageProcMode)

        .function("setDebugMode", &ARToolKitCore::setDebugMode)
        .function("getDebugMode", &ARToolKitCore::getDebugMode)

        .function("getProcessingImage", &ARToolKitCore::getProcessingImage)

        .function("getTransMatSquare", &ARToolKitCore::getTransMatSquare)
        .function("getTransMatSquareCont", &ARToolKitCore::getTransMatSquareCont)
        .function("getTransform", &ARToolKitCore::getTransform);

    /*
     * Error codes specific to this wrapper. These are not ARToolKit5 constants,
     * so they are not generated by @ar-js-org/artoolkit5-constants and must stay
     * bound here.
     */
    constant("ERROR_MARKER_INDEX_OUT_OF_BOUNDS", arjs::artoolkit5::MARKER_INDEX_OUT_OF_BOUNDS);

    /*
     * ARToolKit5 constants are deliberately NOT bound here. They are generated
     * from the same WebARKitLib headers this module compiles against and shipped
     * by @ar-js-org/artoolkit5-constants, which src/index.ts re-exports in full.
     * Binding them a second time would create a source of truth that can drift.
     */
};
