#include "ARToolKitCore.h"
#include <emscripten/bind.h>

using namespace emscripten;
using arjs::artoolkit5::ARToolKitCore;

EMSCRIPTEN_BINDINGS(ARToolKitCore_bindings)
{
    class_<ARToolKitCore>("ARToolKitCore")
        .constructor()
        .function("detectMarker", &ARToolKitCore::detectMarker)
        .function("getMarkerInfo", &ARToolKitCore::getMarkerInfo)
        .function("getMarkerNum", &ARToolKitCore::getMarkerNum)
        .function("teardown", &ARToolKitCore::teardown)
        .function("_loadCamera", &ARToolKitCore::loadCamera)
        .function("setup", &ARToolKitCore::setup)
        .function("addMarker", &ARToolKitCore::addMarker)
        .function("setMarkerInfoDir", &ARToolKitCore::setMarkerInfoDir)
        .function("setMarkerInfoVertex", &ARToolKitCore::setMarkerInfoVertex)
        .function("getCameraLens", &ARToolKitCore::getCameraLens)
        .function("recalculateCameraLens", &ARToolKitCore::recalculateCameraLens)
        .function("passVideoData", &ARToolKitCore::passVideoData)

        .function("setLogLevel", &ARToolKitCore::setLogLevel)
        .function("getLogLevel", &ARToolKitCore::getLogLevel)

        .function("setPatternDetectionMode", &ARToolKitCore::setPatternDetectionMode)
        .function("getPatternDetectionMode", &ARToolKitCore::getPatternDetectionMode)

        .function("setProjectionNearPlane", &ARToolKitCore::setProjectionNearPlane)
        .function("getProjectionNearPlane", &ARToolKitCore::getProjectionNearPlane)

        .function("setProjectionFarPlane", &ARToolKitCore::setProjectionFarPlane)
        .function("getProjectionFarPlane", &ARToolKitCore::getProjectionFarPlane)

        .function("setPattRatio", &ARToolKitCore::setPattRatio)
        .function("getPattRatio", &ARToolKitCore::getPattRatio)

        .function("setMatrixCodeType", &ARToolKitCore::setMatrixCodeType)
        .function("getMatrixCodeType", &ARToolKitCore::getMatrixCodeType)

        .function("setThresholdMode", &ARToolKitCore::setThresholdMode)
        .function("getThresholdMode", &ARToolKitCore::getThresholdMode)

        .function("setThreshold", &ARToolKitCore::setThreshold)
        .function("getThreshold", &ARToolKitCore::getThreshold)

        .function("setLabelingMode", &ARToolKitCore::setLabelingMode)
        .function("getLabelingMode", &ARToolKitCore::getLabelingMode)

        .function("setImageProcMode", &ARToolKitCore::setImageProcMode)
        .function("getImageProcMode", &ARToolKitCore::getImageProcMode)

        .function("setDebugMode", &ARToolKitCore::setDebugMode)
        .function("getDebugMode", &ARToolKitCore::getDebugMode)

        .function("getProcessingImage", &ARToolKitCore::getProcessingImage)

        .function("getTransMatSquare", &ARToolKitCore::getTransMatSquare)
        .function("getTransMatSquareCont", &ARToolKitCore::getTransMatSquareCont)
        .function("getTransform", &ARToolKitCore::getTransform);

    /*
     * Error codes specific to this wrapper. These are not ARToolKit5 constants,
     * so they are not generated by @ar-js-org/artoolkit5-constants and must stay
     * bound here.
     */
    constant("ERROR_MARKER_INDEX_OUT_OF_BOUNDS", arjs::artoolkit5::MARKER_INDEX_OUT_OF_BOUNDS);

    /*
     * ARToolKit5 constants are deliberately NOT bound here. They are generated
     * from the same WebARKitLib headers this module compiles against and shipped
     * by @ar-js-org/artoolkit5-constants, which src/index.ts re-exports in full.
     * Binding them a second time would create a source of truth that can drift.
     */
};
